# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    strategy:
      matrix:
        go: [ '1.21' ]
        platform: [ 'linux', 'windows' ]
        arch: [ 'amd64', 'arm64' ]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run:  CGO_ENABLED=0 GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -o msteams-presence${{ matrix.platform == 'windows' && matrix.arch == 'amd64' && '.exe' || '' }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: msteams-presence-${{ matrix.platform }}-${{ matrix.arch }}
        path: msteams-presence${{ matrix.platform == 'windows' && matrix.arch == 'amd64' && '.exe' || '' }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Create Docker Image
      uses: docker/build-push-action@v2
      if: matrix.platform == 'linux'
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ matrix.platform == 'linux' && matrix.arch == 'amd64' && 'ghcr.io/${{ github.repository }}:latest' || 'ghcr.io/${{ github.repository }}:${{ matrix.platform }}-${{ matrix.arch }}' }}
      