# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

concurrency: 
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha }}
  cancel-in-progress: true

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        go: [ '1.21.4' ]
        platform: [ 'linux', 'windows' ]
        arch: [ 'amd64', 'arm64' ]
    steps:
    - uses: actions/checkout@v4

    - id: lower-repo
      run: |
        echo "image=${GITHUB_REPOSITORY}" | awk '{print tolower($0)}' >> $GITHUB_OUTPUT

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run:  CGO_ENABLED=0 GOOS=${{ matrix.platform }} GOARCH=${{ matrix.arch }} go build -o msteams-presence${{ matrix.platform == 'windows' && matrix.arch == 'amd64' && '.exe' || '' }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: msteams-presence-${{ matrix.platform }}-${{ matrix.arch }}
        path: msteams-presence${{ matrix.platform == 'windows' && matrix.arch == 'amd64' && '.exe' || '' }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      if: matrix.platform == 'linux' && github.event_name == 'push'
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      if: matrix.platform == 'linux' && github.event_name == 'push'
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      if: matrix.platform == 'linux' && github.event_name == 'push'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Create Docker Image
      uses: docker/build-push-action@v5
      if: matrix.platform == 'linux' && github.event_name == 'push'
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ matrix.platform == 'linux' && matrix.arch == 'amd64' && format('ghcr.io/{0}:latest', steps.lower-repo.outputs.image) || format('ghcr.io/{0}:{1}-{2}', steps.lower-repo.outputs.image, matrix.platform, matrix.arch) }}
  
  release:
    needs: build
    runs-on: self-hosted
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3
      with:
        path: artifacts/
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        artifacts: artifacts/*
        generateReleaseNotes: true
        tag: ${{ github.sha }}
        